adrienverge/localstripe

- setup.py
- stripe_mock_server/resources.py
`datetime.replace()` function doesn't manage days from us.
As consequence `(2017, 10, 31).replace(month=11)` will try to create
the date `(2017, 11, 31)` which doesn't exist.
In such case datetime lib crash with the following error:
```
ValueError: day is out of range for month
```
This commit replace the use of `datetime.replace()` to increment month,
by the use of `datetime + relativedelta()`.
`relativedelta()` function is part of `dateutils`, so I also add the
dependency in `setup.py`.
> fix(resources): crash on datetime.replace

- stripe_mock_server/server.py
On one of my laptops, stripe_mock_server took seconds before starting
listening on port 8420. It was because `app.run()` was very long. It
appears to be related to the fact that my system supports IPv6.
Let's listen on `::` (IPv6 version of "any interface"), which is
generally better than `0.0.0.0` because operating systems can map
IPv4 requests to this port, so both IPv4 and IPv6 requests succeed.
More info at https://stackoverflow.com/a/21689979.
And this solves the problem.
Average time between launch and first accepted HTTP request:
- before: 5.48 seconds
- after: 0.40 seconds
> fix(server): Fix long time to start listening on some machines

- stripe_mock_server/resources.py
Some Stripe objects (Account, Charge, Customer, Refund, Subscription,
and Transfer) have metadata. When updating this metadata, absent values
should not be deleted.
This is a bit counter-intuitive, but this is the way the Python Stripe
library works.
For example, updating a Customer with `{"metadata": {"a": 1, "b": 2}}`
then, later, with `{"metadata": {"a": 3}}` should keep `b` unchanged.
> fix(resources): Treat metadata differently

- stripe_mock_server/errors.py
- stripe_mock_server/resources.py
---
From Stripe documentation:
- 4000000000000002  Charge is declined with a card_declined code.
- 4000000000000127  Charge is declined with an incorrect_cvc code.
- 4000000000000069  Charge is declined with an expired_card code.
- 4000000000000119  Charge is declined with a processing_error code.
- 4242424242424241  Charge is declined with an incorrect_number code as
the card number fails the Luhn check.
> Return CardError on special credit card numbers

- localstripe/resources.py
- localstripe/server.py
- test.sh
For example:
curl -u sk_test_abcd: https://api.stripe.com/v1/products \
-d attributes[]=size \
-d attributes[]=gender
---
---
See the change in Stripe API version 2018-02-05:
> Each plan object is now linked to a product object with type=service.
> The plan object fields statement_descriptor and name attributes have
> been moved to product objects.
https://stripe.com/docs/upgrades#2018-02-05
> Plans and product for API version >= 2018-02-05

- localstripe/fake-stripe-v3.js
- localstripe/server.py
Before, the injected fake Stripe JS lib sent requests to
`localhost:PORT`, with `PORT` read from configuration. But when the
server was not accessed from `localhost`, requests from the web page
(add a card, add a SEPA number...) failed because `localhost:PORT` was
not available.
Now, the localstripe server URL is infered from where the JS script is
loaded. For example, if the web page contains:
<script src="http://somehost:6666/js.stripe.com/v3/"></script>
... then calls will be made to:
http://somehost:6666/v1/tokens
http://somehost:6666/v1/sources
> fix(Stripe.js): Issue request to fake server, not localhost

- README.rst
- localstripe/resources.py
Those one works perfectly in my integration tests.
I am using dj-stripe and Products are created in dj-stripe models accordingly.
For plans, it requires to add support to 'usage_type' attribute of stripe plans.
As I've already done this in my fork I'll submit it in another PR.
> Add product.created and plan.created webhooks

- localstripe/resources.py
- test.sh
For instance a query like this should return `null` as `default_source`:
GET /v1/customers/cus_9qtQ75leoBAi7o?expand[]=default_source
Previously, it crashed. Let's also add a test to make sure it doesn't
happen again.
Closes https://github.com/adrienverge/localstripe/issues/32.
> fix(expand): Don't crash when expanding a null value

- README.rst
- localstripe/server.py
Introducing new /_config/store route.
Requesting with method DELETE on it would flush all store data.
This is very useful for me to remove all localstripe data between two integration test.
Edit: squashed
> Add /_config/store route to flush data from store.

- localstripe/resources.py
- test.sh
Adding support for tiered pricing. 
I'm only validating the required `up_to` field in each tier, but happy to add validations for optional fields (`unit_amount` and `flat_amount`) as well. Feel free to ask for it if you think that's gonna be helpful @adrienverge 
This solves issue #44
> feat(Plan): Add support for tiered pricing

- localstripe/resources.py
- test.sh
`id`s are no longer required to create plans since the release of products. 
In this PR I'm changing the behaviour to replicate what the Stripe API does: allow `id`s to be sent optionally, and when not provided generate them with the common pattern `plan_` + unique alphanumeric suffix
This should solve point 2 @nrobates [raised](https://github.com/adrienverge/localstripe/issues/44#issuecomment-455380984)
> Generate plan ids when not given upon creation

- localstripe/resources.py
Since Stripe API version 2018-11-08:
- `paid`, `closed` and `forgiven` have been removed from `Invoice`,
- `status` has been added, it can be `draft`, `open`, `paid`, `void`, or
`uncollectible`.
https://stripe.com/docs/billing/migration/invoice-states#status
> fix(Invoice): Update properties with 'status'

- localstripe/resources.py
- test.sh
Allow providing `tax_id_data`, return `tax_ids`, and drop deprecated
`business_vat_id`.
> feat(Customer): Add support for tax_ids

- localstripe/resources.py
Since Stripe API 2019-03-14, the behavior when creating a subscription
with a failed charge has changed. The new behavior is not implemented in
localstripe, but we can start accepting the `enable_incomplete_payments`
option, which controls this behavior.
https://stripe.com/docs/billing/lifecycle#incomplete-opt-in
> feat(Subscription): Accept enable_incomplete_payments

- localstripe/resources.py
- localstripe/server.py
- test.sh
Unlike JSON data, boolean values sent as
`application/x-www-form-urlencoded` are represented as strings. In this
example `active` has the value `"true"`:
curl $HOST/v1/products -d name=T-shirt -d active=true
Let's decode `"false"` and `"true"` when needed.
---
> Implement tax rates

- localstripe/resources.py
Let's try to do the same as Stripe in test mode:
- by default, verify all tax IDs,
- detect custom values `000000000`, `111111111` and `222222222` like in
https://stripe.com/docs/billing/testing#customer-tax-id-verfication
> feat(tax_ids): Auto-verify tax IDs

- localstripe/resources.py
This is the continuation of commit f90914d "Accept
enable_incomplete_payments", but for subscriptions updates.
> feat(Subscription): Accept enable_incomplete_payments on update

- .travis.yml
Because tests currently fail with:
$ ./test.sh
+HOST=http://localhost:8420
+SK=sk_test_12345
+curl -sSf -u sk_test_12345: http://localhost:8420/v1/customers/ -d 'description=Adding a description...'
curl: (56) Recv failure: Connection reset by peer
The command "./test.sh" exited with 56.
> chore(CI): Temporarily disable Python nightly

- localstripe/resources.py
Otherwise, a request with `?expand[]=dict.property` will permanently
expand `property` in the object (it will no longer be a reference like
`"prop_W9gikYjrX0yGRb"`, but a dict like `{"id": "prop_W9gikYjrX0yGRb",
... }`.
Maybe it's needed to do a deep copy, but I'm not sure (all our Stripe
objects aren't very nested).
> fix(resources): Copy dict when exporting them

- localstripe/localstripe-v3.js
- localstripe/resources.py
- localstripe/server.py
- test.sh
---
---
And adapt localstripe.js to handle `next_action` (for SCA and 3D Secure
cards).
> Implement Payment Methods and Setup Intents

- localstripe/resources.py
- localstripe/server.py
- test.sh
---
For example:
GET /v1/customers/cus_FVPpnJSC?expand[]=tax_ids.data.customer
or:
POST /v1/subscriptions -d expand[]=latest_invoice.payment_intent
> Fix expand in POST, and in nested objects

- localstripe/resources.py
- localstripe/server.py
- test.sh
See https://stripe.com/docs/payments/intents#intent-statuses.
Before:
Subscription ↔ Invoice ↔ Charge
After:
Subscription ↔ Invoice ↔ PaymentIntent ↔ Charge
Note: payment methods that `requires_action` (for instance 3D Secure)
are not yet implemented.
> feat(payment_intents): Implement PaymentIntent objects

- localstripe/localstripe-v3.js
- localstripe/resources.py
- localstripe/server.py
And adapt localstripe.js to handle `next_action` (for SCA and 3D Secure
cards).
---
Based on #73 and #74.
> feat(payment_intents): Implement authentication step

- localstripe/resources.py
This follows commit 89116d9 "fix: Accept booleans passed in
x-www-form-urlencoded", by now accepting all types of booleans, even
`True` or `FALSE`.
It seems necessary when using the Stripe Python library with boolean
parameters (like `enable_incomplete_payments=False`).
> fix: Accept various types of boolean strings

- localstripe/resources.py
From Stripe docs:
> [Invoice creation] returns an error if there are no pending invoice
> items
> fix(invoices): Prevent creation of empty invoices

- localstripe/resources.py
When invoice amount is zero, it is automatically marked as `paid`. The
subscription creation failed. Let's fix that.
> fix(subscriptions): Fix error on free invoice

- localstripe/resources.py
- test.sh
Customer._get_default_payment_method_or_source() returns a Card/Source/PaymentMethod object, not a string, so when only a customer is provided, you get an error like:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
resp = await task
File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/root/localstripe/localstripe/server.py", line 56, in error_middleware
return await handler(request)
File "/root/localstripe/localstripe/server.py", line 192, in auth_middleware
return await handler(request)
File …
```
> bugfix: only parse charge source as a string if it is one

- localstripe/resources.py
- test.sh
on real stripe, `POST /v1/charges` immediately processes the payment (or preauthorizes the funds for later when `capture=false`), and if this fails the response will be a 402 status code, with the [charge id](https://stripe.com/docs/api/errors#errors-charge) included in the response body.
> declined charge - 402 on create API

- localstripe/resources.py
`tax_amounts` is the expression of a `TaxRate` on an amount, as describe here
for an invoice line item:
https://stripe.com/docs/api/invoices/line_item#invoice_line_item_object-tax_amounts
We will re-use it when applying an invoice `default_tax_rate` in a future
commit so let's move it inside the `TaxRate` object.
---
From Stripe [`invoice creation API`], implement `default_tax_rates` parameter.
Subscriptions are not impacted yet (no `default_tax_rates` on subscription).
Revert part of the commit [`feat(invoices): Implement default_tax_rates`] that
wasn't saving `default_tax_rates` in the Invoice object and leads to various
issues.
[`invoice creation API`]: https://stripe.com/docs/api/invoices/create#create_invoice
[`feat(invoices): Implement default_tax_rates`]: …
> `default_tax_rate` for invoice and subscription

- localstripe/resources.py
- localstripe/server.py
- test.sh
@rasmuscnielsen for info. This your commit (taken from https://github.com/adrienverge/localstripe/pull/101) with a few fixes:
```diff
--- a/localstripe/resources.py
+++ b/localstripe/resources.py
@@ -738,8 +738,7 @@ class Customer(StripeObject):
@classmethod
def _api_add_subscription(cls, id, **data):
-        obj = Subscription(customer=id, **data)
-        return obj
+        return Subscription._api_create(customer=id, **data)
@classmethod
def _api_retrieve_subscription(cls, id, subscription_id, **kwargs):
@@ -749,7 +748,8 @@ class Customer(StripeObject):
obj = Subscription._api_retrieve(subscription_id)
if obj.customer != id:
-            raise UserError(400, 'Customer ' + id + ' does not have a subscription with ID ' + subscription_id)
+            raise UserError(404, 'Customer ' + …
```
> feat(customer): Add subscription endpoints

- localstripe/resources.py
If no items field is given, we'll check for plan and quantity directly in the root object.
This is in accordance with Stripe's API and how the official PHP-SDK works.
> Support legacy 'plan' and 'quantity'

- localstripe/resources.py
When updating a subscription without sending a plan-id, it will simply stay on the same plan.
This is in accordance with the official stripe api.
> Allow updating a subscription without a plan id

- localstripe/resources.py
- test.sh
Function `_set_up_subscription_and_invoice()` of Subscription class, did:
- plan upgrade,
- subscription items update,
- previous invoice un-used time item creation (only on update)
- and, if needed, next invoice creation.
I think it is un-easy to modify to create new features.
I propose to break-it in smaller parts.
---
Before, calling `/subscription/id` two times with the same parameters was
re-creating part of the subscription:
- it'd recreate the subscription items and thus changed their ids
- it'd re-setup the plan and thus changed `current_period_start` and
`current_period_end`
---
It allow to designate a subscription with his ID only, and update a small part
of it, like in this Stripe documentation extract:
```
curl https://api.stripe.com/v1/subscriptions/sub_GDjt2p38WYqAzx \
-u …
```
> Subscription update

- localstripe/localstripe-v3.js
From a careful riding of the Stripe documentation, it seems that [`Element`]
does not have a `address_zip` field, but a `value.postal_code` field.
In the meantime, the function [`handleCardSetup()`] that consume it, seems
to look for postal code inside
`data.payment_method.billing_details.address.postal_code`, because, in the
background, it use the [`PaymentMethod`] API.
Let's use this structure, it will easy future compatibility with new
[`confirmCardSetup()`].
User be able to call the API like that which wasn't possible before:
```
Stripe().handleCardSetup(clientSecret, {
{
"number": "4242424242424242",
"exp_month": 12,
"exp_year": 2020,
"cvc": "314",
},
payment_method_data: {
billing_details: {
address: {
postal_code: '12345',
},
},
},
});
```
[`Element`]: …
> Stripe JS handleCardSetup and handleCardPayment renaming

- localstripe/resources.py
- test.sh
See officiel Stripe docs: these are `null` when unset.
---
---
Fixes https://github.com/adrienverge/localstripe/issues/112.
> Support customer 'phone' and 'address'

- localstripe/resources.py
As per issue #115 
This just defaults the start_date to the current time, which fixes our immediate use-case. I am regrettably not familiar enough with the Stripe APIs to know if it's correct in all cases.
I am not sure if anything needs to be added to test.sh - I find the file a bit hard to read.
I'm happy to discuss this issue further.
> Add start_date field when creating a subscription

- localstripe/resources.py
- test.sh
Like the real Stripe API does.
> fix(expand): Accept max 4 levels of a property

- localstripe/resources.py
- test.sh
Stripe API is returning `InvoiceLineItem`s in its latest version
instead of `InvoiceItem`s as it may have in the past.
This new object acts as a representation of either an
`InvoiceItem` or a `SubscriptionItem` for each line of an `Invoice`.
More info on [Stripe's documentation](https://stripe.com/docs/api/invoices/line_item).
Let's support them in localstripe!
> feat: Support invoice line items (il_) from Stripe API 2019-12-03

- localstripe/resources.py
This adds the "cancel_at" attribute to Subscriptions object.
This does not implement any behaviour related to the attribute, it merely stores it when a subscription is updated.
Documentation: https://stripe.com/docs/api/subscriptions/update#update_subscription-cancel_at
> Add "cancel_at" attribute to Subscriptions object

- localstripe/resources.py
- test.sh
That's what real Stripe does, e.g. on a plan upgrade:
```yaml
[
{
"id": "il_1GbU4aKxWWXl12QBOzUyETIM",
"type": "invoiceitem",
"subscription_item": "si_H9nhRadSKnHfBu",
"invoice_item": "ii_1GbU4bKxWWXl12QBhGX2ce3u",
"amount": -1000,
"description": "Unused time on Plan after 24 Apr 2020",
"plan": { "id": "monthly-plan", ... },
"proration": true
},
{
"id": "il_1GbU4bKxWWXl12QCMJnxK6Ws",
"type": "subscription",
"subscription_item": "si_H9nhRadSKnHfBu",
"amount": 9900,
"currency": "eur",
"description": "1 × Plan (at €99.00 / year)",
"plan": { "id": "yearly-plan", ... },
"proration": false
}
]
```
---
This fixes a bug when a subscription is upgraded to another plan with a
different billing cycle (e.g. monthly to yearly). In such a case, the
invoice is generated when the user creates the invoice …
> Fix incorrect invoice lines on subscription plan upgrade

- localstripe/resources.py
This fixes the following bug: if a subscription was upgraded to a plan
with the same billing cycle (e.g. yearly → yearly), and the user
generated the invoice manually, then the `Subscription.latest_invoice`
wasn't updated to the new value.
> Subscription: Correctly set latest_invoice on manual payment

- localstripe/resources.py
Log of the CI before this commit:
```
$ if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then flake8 .; fi
./localstripe/resources.py:594:47: E741 ambiguous variable name 'l'
The command "if [[ $TRAVIS_PYTHON_VERSION != nightly ]]; then flake8 .; fi"
exited with 1.
```
> refactor: Rename a variable to fix lint rule E741

- localstripe/resources.py
This allows converting values like `"50.0"` which is what stripe-go will post for the `percent_off` value in POST coupon.
Sorry I'm not much of a python guy, so I'm not sure if the double try is very idiomatic. I'd be happy to change it if you have a better suggestion.
Thanks
> convert: add double convert to int on error

- localstripe/resources.py
Since commit 4810d4b _coupon: use float value for percent_off_ the following
unit test is failing:
```
...
+ curl -sSf -u sk_test_12345: http://localhost:8420/v1/coupons -d id=PARRAIN
-d percent_off=30 -d duration=once
curl: (22) The requested URL returned error: 400 Bad Request
```
It's because, in the code just after 4810d4b change, the expected type for
`percent_off` is still `int`.
> fix(resources): Check that coupon `percent_off` is float not int

- localstripe/resources.py
Let's add the property `billing_reason` that was missing. For the
moment, it's not implemented so it's always `null`.
https://stripe.com/docs/api/invoices/object#invoice_object-billing_reason
> Invoice: Add 'billing_reason' property

- .travis.yml
- test.sh
Problem: very recently, Travis started to fail on commit that were
previously fine. Probably a change on their side?
It appears that on some Python version (e.g. 3.7 but not 3.8) they
double-escape `%5B` and `%5D` caracters, so they are passed as `%255B`
and `%255D`.
To avoid that, I propose to use `[` and `]` directly, and enable curl's
`-g` option (`--globoff`) so that it doesn't interpret them.
In summary now the commands are a bit clearer:
curl -sSfg -u $SK: $HOST/v1/plans?expand[]=data.product
---
And drop support on Python 3.5 and 3.6.
> Support Python 3.8 and 3.9 and fix Travis problem

- localstripe/resources.py
`None` is already the implicit default when using `get()` on a dict.
> refactor: Remove useless 'None' argument in dict.get()

- localstripe/resources.py
This does not attempt to replicate Stripe's handling of non-ASCII characters statement_descriptor.
> Charge: add statement_descriptor property

- localstripe/server.py
Localstripe uses the `store` object to store data between localstripe executions.
But I just noticed that some TaxRate attributes are not saved properly.
It's the case for a few properties of the TaxRate object.
Reproduction:
- launch localstripe from scratch `python3 -m localstripe --from-scratch`
-
$ curl -sSfg -u sk_test_12345: http://localhost:8420/v1/tax_rates \
-d display_name=VAT  -d description='TVA France taux normal' \
-d jurisdiction=FR -d percentage=20.0 -d inclusive=false
{
"active": true,
"created": 1616511744,
"description": "TVA France taux normal",
"display_name": "VAT",
"id": "txr_hG2CLNRGQMy35a",
"inclusive": false,
"jurisdiction": "FR",
"livemode": false,
"metadata": {},
"object": "tax_rate",
"percentage": 20.0
}
- Kill localstripe
- Relaunch localstripe `python3 -m …
> Server: Dump the store after PUT POST and DELETE requests

- localstripe/resources.py
This commit makes the assumption that invoices in localstripe are either
fully paid (amount_paid == amount_due) or not paid at all (amount_paid =
0).
This behavior can be different with real Stripe servers.
Tested with my end-to-end tests without any error.
> feat(invoice): Add amount_paid attribute

- localstripe/resources.py
**InvoiceItem: Make tax_rates property default to an empty array**
Real Stripe servers return an empty array if there is no tax rates on an
InvoiceItem object. Let's do that in localstripe too.
https://stripe.com/docs/api/invoiceitems/object#invoiceitem_object-tax_rates
---
**SubscriptionItem: Make tax_rates property default to an empty array**
Real Stripe servers return an empty array if there is no tax rates on a
SubscriptionItem object. Let's do that in localstripe too.
https://stripe.com/docs/api/subscription_items/object#subscription_item_object-tax_rates
> Make tax rates properties default to empty array when unset

- localstripe/resources.py
- test.sh
This PR adds several improvements to listing products, plans, customers, and subscriptions (stripe features that we use at @localstack)
* 3e46219: adds a dedicate list method for `/v1/products` to take the optional `active=true|false` keyword
* 92e1e15: same deal, adds filters for `/v1/plans`
* dfdccaf: enables the optional `object=card` filter argument to `/v1/customers/{id}/sources`
* 1423038: allows the `trial_from_plan` boolean flag for `/v1/subscriptions`
I tried to conform to the semantic commit messages i found in the history, and tried to keep the code style as close to the original code as possible.
Happy to make changes.
> add several list filtering improvements

- localstripe/resources.py
Let's add the property `collection_method` that was missing.
For the moment, it's not implemented so it's always
`charge_automatically`.
https://stripe.com/docs/api/invoices/object#invoice_object-collection_method
> Invoice: Add 'collection_method' property

- test.sh
Everywhere in the `test.sh` file, when we use the `grep` command,
we try to catch a complete line and especially with the end comma.
Like here:
https://github.com/adrienverge/localstripe/blob/7f298f2/test.sh#L260 .
Let's add missing commas.
> tests: Add missing commas

- localstripe/resources.py
- test.sh
As described here
https://stripe.com/docs/api/customers/list#list_customers-email,
the Stripe API allows you to find one or more customers by their
email addresses by adding the query param `?email=<something>`
to the `/v1/customers` route.
Stripe doesn't care about the format of the emails we send in
the request, as long as they are strings.
If we request with an unknown address, it returns an empty list.
On the other hand, if we request with a known address, it returns
a list of customers who have this address in their email field.
So there can be several customers with the same email address.
Let's emulate this behavior.
Closes: https://github.com/adrienverge/localstripe/pull/154 https://github.com/adrienverge/localstripe/issues/153
> feat(customers): Find customers by email

- localstripe/resources.py
- test.sh
Here is the Stripe documentation for balance at Customer creation:
Current balance, if any, being stored on the customer. If negative, the customer
has credit to apply to their next invoice. If positive, the customer has an
amount owed that will be added to their next invoice. The balance does not
refer to any unpaid invoices; it solely takes into account amounts that have
yet to be successfully applied to any invoice. This balance is only taken
into account as invoices are finalized.
I tried to make a basic implementation of it, I hope it's close enough to
what Stripe does.
----
When an Invoice doesn't have a Charge, and we
`-d expand[]=data.charge.refunds` that Invoice, the current code crash because
it cannot loop over a null Charge to find Refunds in it.
When one of the keys in the …
> Balance & expand crash

- localstripe/resources.py
This commit adds the property to the Invoice creation call to avoid crashing, 
but it doesn't implement or test its behavior.
> Invoice: Add pending_invoice_items_behavior property

- localstripe/resources.py
- localstripe/server.py
- test.sh
The goal is to be closer to Stripe API. Also, create a new DeletedObject class
that will be easier to use.
---
Creating and listing TaxID have been supported for a long time, but retrieving
or deleting a single TaxID wasn't implemented, so let's change that.
Stripe doc:
- https://stripe.com/docs/api/customer_tax_ids/retrieve
- https://stripe.com/docs/api/customer_tax_ids/delete
> TaxID: Expand API to allow retrieving or deleting a single TaxID

- localstripe/resources.py
- localstripe/server.py
The right way to compare primitive types in Python is to use the exact comparison `is`.
This shuts up the flake8 linter, currently complaining on master branch.
> style: Compare Python types with `is`, not `==`

- localstripe/localstripe-v3.js
It can be desirable to use localstripe from a user-defined URL with a custom path, e.g.:
https://domain/subpath/js.stripe.com/v3/
https://domain/subpath/v1/payment_intents/
https://domain/subpath/v1/customers/cus_S5TdpWqIoiuKlq/sources
instead of:
http://domain:8420/js.stripe.com/v3/
http://domain:8420/v1/payment_intents/
http://domain:8420/v1/customers/cus_S5TdpWqIoiuKlq/sources
This can be achieved by using a reverse-proxy for example, but the JavaScript part of localstripe didn't support it.
This commit fixes that by dynamically computing the base API URL from which the JavaScript code is loaded.
> API: Allow serving localstripe API from a custom URL

- localstripe/resources.py
There is no `self` when there is no instance. Only the static class `cls` means anything in such context. As the linter says:
N804 first argument of a classmethod should be named 'cls'
> style: Use 'cls' (not 'self') in class methods

- .github/workflows/tests.yaml
Python 3.7 end of life was on 2023-06-27, 5 months ago.
> Support Python versions ≥ 3.8

- .github/workflows/tests.yaml
Commit c088710 "Support Python versions ≥ 3.8" added CI tests for Python 3.10, for YAML simplifies 3.10 to 3.1 (it's a number), which is not what we want.
Let's be explicit about 3.10 (and in the future 3.20, 3.30, etc.)
> CI: Fix tests run on Python 3.10

- localstripe/resources.py
- test.sh
localstripe already supports Charges with pre-auths and refunds, and it supports PaymentIntents without pre-auths or refunds.
Since PaymentIntents are either preferred or supported for most APIs now, let's support pre-auths on PaymentIntents! Since the PaymentIntent implementation in localstripe just proxies most stuff onto Charge objects, we can proxy pre-auths onto them too. Same for refunds.
We are already using this at Via (ridewithvia.com) to test our Stripe integration.
The tests are a big copy-paste-modify on the Charges tests, which seem pretty comprehensive... and we add tests for refunds on both Charges and PaymentIntents.
> Support preauth and refunds on PaymentIntents

- localstripe/localstripe-v3.js
This continues commit c89bb15 "API: Allow serving localstripe API from a custom URL" by simplifying the way to get localstripe server URL, and also fixes the case when `localstripe.js` is loaded dynamically (in this case, `document.getElementsByTagName('script')` references the wrong element: the calling/parent `<script>`) like this:
let script = document.createElement('script');
script.type = 'text/javascript';
script.src = 'http://localhost:8420/js.stripe.com/v3/';
document.head.appendChild(script);
> localstripe.js: Fix LOCALSTRIPE_BASE_API on dynamical load

- localstripe/resources.py
'au_abn' and 'nz_gst' are numbers with only digits, they don't contain their
country code.
We can only guess the country from 'eu_vat' taxIDs, so let's adapt the code to
better handle AU and NZ taxIDs number.
See [the Stripe documentation] for the exact format of these two taxIDs number.
[the Stripe documentation]: https://docs.stripe.com/billing/customer/tax-ids
---
According to Stripe's documentation[^1], two Spanish Customer Tax IDs (`eu_vat`
& `es_cif`) are supported.
[^1]: https://docs.stripe.com/billing/customer/tax-ids#supported-tax-id-types
Let's add the support for Spain's _código de identificación fiscal_ (CIF) tax
ID.
Even if Stripe doesn't validate this type of Customer Tax ID (unlike EU
VAT)[^2], the related dashboard form input only checks if the given value's
length is 9. …
> TaxID: Add support for Spanish CIF

- localstripe/resources.py
- test.sh
Previously localstripe only supported confirmation of SetupIntents with payment_method_data, which is a dictionary containing the information needed to create a PaymentMethod. The Stripe SetupIntents API also allows the caller to pass in an already-created PaymentMethod, by ID. This change adds that capability to localstripe.
I also added a few of the canonical test articles you can use as a payment method ID. These generally map 1:1 with the test card numbers.
> Support confirmation of SetupIntents with a payment method ID

- localstripe/resources.py
- test.sh
I added the ability to add a payment method by ID on confirm here: https://github.com/adrienverge/localstripe/pull/226
Per testing with the actual Stripe API, and common sense, we should return a 400 error if neither payment_method nor payment_method_data are supplied to the confirm request (the point of the confirm is to add a payment method, so it makes no sense to call confirm with no payment method). So I added validation and changed an old test case that seemed to be asserting a behavior unlike what Stripe actually does.
This also addresses a one-liner review comment from this PR: https://github.com/adrienverge/localstripe/pull/226
I was resetting payment_method_types within the confirm handler. Upon testing, this is not what the real Stripe API does, so I removed that recent …
> Fail if no payment method on confirm

- test.sh
This adds a small suite of tests related to the discussion at https://github.com/adrienverge/localstripe/pull/232#issuecomment-2400000513
It seems that Stripe works this way (I've tested it today), so let's make sure Localstripe does it too, by adding a non-regression test.
> Subscription: Test that creation with card 4000000000000341 works

- .github/workflows/tests.yaml
GitHub is rolling out `ubuntu-24.04` as the new `ubuntu-latest` on GitHub
Actions[^1]. Previously it was `ubuntu-22.04`.
There are many small breaking changes that people are complaining about in
this update[^2].
Localstripe is impacted by the fact that `pip` now fails on installing a paquet
system-wide with the following error:
```
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a …
```
> CI: Install python3-build & add --break-system-packages for Localstripe

- localstripe/resources.py
- test.sh
Before this change we were erroneously marking pre-auth'd charges as status=pending, when they're actually status=succeeded. We were (accidentally) working around this incorrect behavior in pre-auth'd PaymentIntents.
To get this right we have to actually split the _trigger_payment method into two: a check for payment authorization (which we do on construction even for Charges created with capture=false), and a separate routine to actually capture the charge (which we do on construction for non-pre-auth'd charges, and on _api_capture for pre-auth'd charges). We also split the PaymentIntent._api_confirm method into two for more control of error handling. We then adjust the PaymentIntent wrapper to fit.
This also fixes a tiny mistake in the Charge refund test; it was asserting the wrong …
> Fix pre-auth behavior

- .github/workflows/tests.yaml
This reverts commit 1ad01ad "CI: Install python3-build & add --break-system-packages for Localstripe", merged 5 days ago.
Since then, the CI broke again, with errors like:
$ python -m build
RuntimeError: Virtual environment creation failed, executable /tmp/build-…/local/bin/python missing
I found that using our previous `pip install` commands worked. GitHub or Ubuntu maintainers probably fixed the inconveniences described by Hoël at https://github.com/adrienverge/localstripe/pull/234.
> CI: Restore previous pip install method

- localstripe/resources.py
- test.sh
These features are technically separate but it's easier to test them together.
The Stripe event query API lets us filter by event type and timestamp.
Meanwhile payment_intent successes and failures generate events (this is particularly important for sepa_direct_debit which on the real Stripe API is typically pending for days, on the Stripe test API is typically pending for a minute or so, and in localstripe is pending for 0.5 seconds).
> Add event querying and payment_intent events

- localstripe/resources.py
[Stripe documentation on invoices] describes this field like this:              
> customer_email - nullable string                                              
>                                                                               
> The customer’s email. Until the invoice is finalized, this field will equal   
> customer.email. Once the invoice is finalized, this field will no longer be   
> updated.                                                                      
This is the field that should be used to know where an invoice was effectively  
sent (when using Stripe or a third-party solution to send invoices by email)    
Note that the current implementation only updates the field on invoice          
finalization to keep the implementation simple. …
> Invoice: Add `customer_email` in invoice object

- localstripe/resources.py
- test.sh
When computing taxes, Stripe uses the 'commercial round' strategy, meaning that 
0.5 will be rounded to 1 (when rounding to an integer) as stated here:          
https://docs.stripe.com/billing/taxes/tax-rates#rounding                        
Localstripe behaves differently, because to achieve rounding it casts the       
resulting `float` to an `int` with the line:                                    
`'amount': int(amount * self.percentage / 100.0)`                               
But casting to an `int` doesn't use the same rounding strategy, indeed the      
Python documentation says:                                                      
> For floating-point numbers, this truncates towards zero.                      
So this effectively rounds 0.5 to 0, which is different from Stripe …
> Taxe Rate: Use same rounding strategy as Stripe for tax amounts

- localstripe/resources.py
- test.sh
The Upcoming Invoice API is deprecated and removed since API version 2025-03-31:
https://docs.stripe.com/changelog/basil/2025-03-31/invoice-preview-api-deprecations
The new Create Preview Invoice API is almost the same and only the parameters structure changed.
Reference: https://docs.stripe.com/api/invoices/create_preview
> Invoice: Add support for Create Preview Invoice API
