adrienverge/localstripe

stripe_mock_server/resources.py
Commit 242e6bdfbaaf00c89ee64ff580c1dda691c6fae1, which aimed at fixing
a crash, removed some lines it shouldn't have.
Let's revert thoses two lines deletion.
=> fix(resources): fix previous fix

localstripe/errors.py, localstripe/resources.py, localstripe/server.py, setup.py
aiohttp allows to run coroutines, and has much better performance than
Flask.
=> feat(server): Replace Flask with aiohttp

localstripe/resources.py, test.sh
=> feat(customers): Allow creating a customer with a source

localstripe/resources.py, localstripe/server.py
Allow stripe events to be retrieved.
Edit: Squashed
=> Allow retrieving Event stripe objects.

.travis.yml, README.rst
=> chore(CI): Lint README.rst

test.sh
=> test(customer): Add a test to expand default_source

localstripe/resources.py
=> Do not hard-code currency

localstripe/resources.py
Previously, creating an invoice with a bad credit card would make the
charge fail, but getting the invoice later would still return a HTTP 402
forever.
The HTTP 402 error should be returned only when creating the invoice or
subscription. After that, querying the invoice object should return it,
with `paid: false` and the charge being `failed`.
=> fix(Subscription): Don't perpetually raise error if charge failed

localstripe/resources.py, test.sh
This should fix the issues @nrobates is describing in https://github.com/adrienverge/localstripe/issues/44 where subscriptions to plans with tiered billing failed because of how the invoices where expecting a plan amount to be given (which is not there for tiered plans). In this PR I also added support for having multiple subscriptions to the same plan, as otherwise plan quantities were always treated as 1, which limited the benefits of using tiered pricing.
Still pending are changes to allow subscribing to different plans in the same subscription, and making the upcoming invoice endpoint work with tiered billing. 
The latter will probably require a refactor to reuse the logic used to calculate the amounts introducing a `Tier` class. That is likely to take some time, so in order to make …
=> Add support for multiple plans and tiered billing in invoices

localstripe/resources.py, test.sh
This commit tries to implement usage of `tax_rates`, and deprecates
`tax_percent`.
=> feat(invoices): Use tax_rates in invoices and subscriptions

localstripe/localstripe-v3.js, localstripe/server.py, setup.py
=> localstripe.js and on('change', function)

localstripe/resources.py
=> Implement status 'void' for invoices

localstripe/resources.py
=> Implement API /v1/invoices/:id/void

localstripe/resources.py
=> Cards: Add missing 3D Secure numbers and _requires_authentication()

localstripe/resources.py
On top of #73 and #77.
---
In order to make the transition to new Stripe subscriptions easier
(especially for `enable_incomplete_payments=true` /
`payment_behavior=allow_incomplete`), let's refactor the way errors are
handled, in a more understandable way.
HTTP 402 errors are now only returned for subscription creation
failures (and attaching a wrong card to a customer, also).
=> refactor: Handle payments with _on_failure_now and _on_failure_later

localstripe/resources.py
This is not what Stripe does. Only trigger payment when a subscription
invoice is created.
=> fix(invoices): Do not pay invoices on creation

localstripe/resources.py
From Stripe docs:
> Switching plans does not normally [...] generate an immediate charge.
> The exception is when you're switching between different intervals
> (e.g., monthly to yearly) [...]
=> fix(subscriptions): Create an invoice on update if different interval

localstripe/resources.py
This changes implements the new subscription behavior:
`payment_behavior=allow_incomplete|error_if_incomplete` (or
equivalently: `enable_incomplete_payments=true|false`, but this seems to
be deprecated now).
Warning: this commit also enables the option by default (like Stripe
does for API versions >= 2019-03-14). If you don't want this, pass
`enable_incomplete_payments=false` or
`payment_behavior=error_if_incomplete` when creating / updating a
subscription.
=> feat(subscriptions): Implement enable_incomplete_payments

localstripe/resources.py, test.sh
accept the capture parameter in charge creation, and create `POST /v1/charges/:id/capture`
=> add support for pre auth charges (charge capture param)

localstripe/resources.py
This fixes a bug introduced by commit 6fc05fd "By default created
invoices are drafts": since then, invoices creation didn't fail with
HTTP 400 when it should.
=> fix(invoices): Distinguish between upcoming and draft

localstripe/resources.py, test.sh
a source fingerprint is supposed to always remain the same for the same source. this makes it so :)
=> preserve source fingerprint across times added

localstripe/resources.py, test.sh
since updating and deleting cards/sources does not happen on the basic `/v1/sources/{id}` path, adds paths to support them at `v1/customers/{customer_id}/sources/{source_id}` that hook into the main `Source._api_delete` and `Source._api_update`
=> support for update + delete source

localstripe/resources.py
- allow the name field for customers
- add trial_period_days field
- when on a free trial don't invoice (specified by trial_end or trial_period_days)
=> resource field updates

localstripe/resources.py
@rasmuscnielsen for info. This your commit (taken from #101) with a few fixes.
=> feat(subscription): Add support for trial_end and cancel_at_period_end

localstripe/server.py, test.sh
Fixes https://github.com/adrienverge/localstripe/issues/120.
=> fix(expand): Support expand in extra APIs

localstripe/resources.py
This changes the start date of the subscription when it's created.
Documentation: https://stripe.com/docs/api/subscriptions/create?lang=curl#create_subscription-backdate_start_date
=> Add "backdate_start_date" property to Subscription

localstripe/resources.py
I have added these two keys to the subscription object as they are part of the current Stripe API.
The server only runs type checks on the new values if provided and assigns the billing_cycle_anchor
as a property of the subscription (just like in the Stripe API).
Let me know if you think more tests are needed for this.
(And thanks again for the work on this **massively time saving** project!)
=> feat(subscription): add billing_cycle_anchor and proration_behavior

localstripe/resources.py, test.sh
=> Added off_session and confirm to PaymentIntent creation

localstripe/resources.py
`confirm` and `off_session` are not part of the object itself. They are
read only on *creation*, and used only once to confirm the intent:
From https://stripe.com/docs/api/payment_intents/create:
> When `confirm=true` is used during creation, it is equivalent to
> creating and confirming the PaymentIntent in the same call.
> You may use any parameters available in the confirm API when
> `confirm=true` is supplied.
---
@ImJustToNy this follows #133 and #135. Can you review it or test it? Thanks!
=> PaymentIntent: Refactor passing of confirm and off_session

localstripe/resources.py, test.sh
Made from Stripe documentation:
https://stripe.com/docs/api/charges/list#list_charges-customer
--- 
~~This PR is based on top of the other PR https://github.com/adrienverge/localstripe/pull/141~~
=> Charge: Add `customer` and `created` to the list API

localstripe/resources.py
… return callstack in UserError
Resolves #150
=> type not required in creating product

localstripe/resources.py
=> Add missing metadata to SubscriptionItems

localstripe/resources.py, test.sh
implements `starting_after` query param for `List` as noted in #168
=> List pagination: starting_after

localstripe/resources.py, test.sh
=> Balance resource implementation

localstripe/resources.py, localstripe/server.py, test.sh
=> Payouts implementation

localstripe/localstripe-v3.js
* Add stubbed createPaymentMethod
* Add getElement to elements in JS client
* Fix typo in createToken
* Add unmount and destroy to Element
This fixes #147.
=> localstripe.js: Make compatible with react-stripe-js

localstripe/resources.py, test.sh
Stripe's customer creation endpoint accepts a `payment_method` parameter. This adds the parameter to the localstripe mock.
Ref: https://stripe.com/docs/api/customers/create#create_customer-payment_method
=> Add payment_method to customer creation endpoint

CONTRIBUTING.rst, README.rst
There was a few cases of hard-to-review PR lastly, the goal of this new
CONTRIBUTING.rst is to help us answer these PRs quickly.
=> docs: Add CONTRIBUTING.rst file
